# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel's Garage Office
email: chipchoc@hanmail.net
description: > # this means to ignore newlines until "baseurl:"
  This blog posts various coding or research stuff for personal storage purpose. I am interested in Computer
   vision, deep learning, c/c++, shell scripts, SW algorithms, and etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabriel-kang.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Gabriel-Kang

# Build settings
markdown: kramdown
#highlighter: pygments

# 마크다운 처리기
kramdown:
    input: GFM